### ISSUE TITLE
Simplify GHC API use

### ISSUE THREAD

**Issue by adamgundry** [adamgundry/uom-plugin#46]
Given that the GHC API is subject to change between compiler releases (including moving where definitions are exported from), it would be much simpler if rather than importing GHC API modules directly, we had a single module that re-exported everything from the GHC API required by the plugin. That module could also be used for compatibility shims to cover differences in GHC versions.

Relatedly, I suspect the instance-only import of `TcType` introduced in #45 can be removed.

**Comment by philderbeast** [comment]
Please assign this issue to me.

**Comment by philderbeast** [comment]
I've pulled all the GHC API imports into a single `GhcApi` module;

```
uom-plugin/src/
├── GhcApi
│   ├── Compare.hs
│   ├── Shim.hs
│   └── Wrap.hs
└── GhcApi.hs
```

I've got the `uom-plugin` itself building these ways, 

```
> stack build uom-plugin --stack-yaml=stack-8.0.1.yaml
> stack build uom-plugin --stack-yaml=stack-8.0.2.yaml
> stack build uom-plugin --stack-yaml=stack-8.2.2.yaml
> stack build uom-plugin --stack-yaml=stack-8.4.3.yaml
> stack build uom-plugin --stack-yaml=stack-8.6.1.yaml
```

I set aside trying to compile with `ghc-7.10.2` and `ghc-7.10.3`, also available as stackage LTS resolvers. I would have had to deepen the maze of #ifdefs to achieve this.

The `uom-plugin-examples` that were building, continue to do so;

```
> stack build uom-plugin-examples --stack-yaml=stack-8.0.1.yaml
> stack build uom-plugin-examples --stack-yaml=stack-8.0.2.yaml
> stack build uom-plugin-examples --stack-yaml=stack-8.2.2.yaml
```

I'm seeing problems building the rational examples with `ghc-8.4.3`;

```
> stack build uom-plugin --stack-yaml=stack-8.4.3.yaml
*** Core Lint errors : in result of Desugar (after optimization) ***
<no location info>: warning:
    [in body of letrec with binders $d(%,%)_adlx :: (((Any :: Unit)
                                                      ~ (Any :: Unit),
                                                      () :: Constraint),
                                                     () :: Constraint)]
    From-type of Cast differs from type of enclosed expression
    From-type: (((Base "m" :: Unit) ~ (Base "m" :: Unit),
                 () :: Constraint),
                () :: Constraint)
    Type of enclosed expr: (((Any :: Unit) ~ (Any :: Unit),
                             () :: Constraint),
                            () :: Constraint)
    Actual enclosed expr: $d(%,%)_adlx
    Coercion used in cast: ((%,%)
                              (((%,%)
                                  ((~) <Unit>_N (Sym (R:CanonicalBaseUnit"m"[0])) <Base "m">_N)_N
                                  (Sym (D:R:AllIsCanonical[0])))_N ; Sym (D:R:AllIsCanonical[1]
                                                                              <"m">_N <'[]>_N))
                              (Sym (D:R:AllIsCanonical[0])))_R ; (Sub (Sym (D:R:IsCanonical[0]
                                                                                <'["m"]>_N
                                                                                <'[]>_N)) ; (IsCanonical
                                                                                               <'["m"]
                                                                                                ':/ '[], Unpack
                                                                                                           (Base
                                                                                                              "m")>)_R)
*** Offending Program ***
...
```

I'm also seeing problems building the rational examples with `ghc-8.6.1`;

```
> stack build uom-plugin --stack-yaml=stack-8.6.1.yaml
*** Core Lint errors : in result of Desugar (before optimization) ***
<no location info>: warning:
    In the coercion ‘Sym (Sym (D:R:ToCBU[0]
                                   <'["m"]>_N <'[]>_N ; Sym (Sym (D:R:ListToCBU[1]
                                                                      <"m">_N
                                                                      <'[]>_N ; Sym (Sym (R:CanonicalBaseUnit"m"[0] ; co_abMD)
                                                                                     *: Sym (D:R:ListToCBU[0]))_N)
                                                             /: Sym (D:R:ListToCBU[0]))_N) ; (ToCBU
                                                                                                ((Sym co_abMg ; Sym co_abMF) ; (Unpack
                                                                                                                                  (Sym co_abMD))_N))_N) ; (Sym (D:R:ToCBU[0]
                                                                                                                                                                    <'["km"]>_N
                                                                                                                                                                    <'[]>_N ; Sym (Sym (D:R:ListToCBU[1]
                                                                                                                                                                                            <"km">_N
                                                                                                                                                                                            <'[]>_N ; Sym (Sym (D:R:CanonicalBaseUnit"km"[0] ; (D:R:MkUnit"m"[0] ; co_abMD))
                                                                                                                                                                                                           *: Sym (D:R:ListToCBU[0]))_N)
                                                                                                                                                                                   /: Sym (D:R:ListToCBU[0]))_N) ; (ToCBU
                                                                                                                                                                                                                      ((Sym co_abMh ; Sym co_abMJ) ; (Unpack
                                                                                                                                                                                                                                                        (Sym co_abMH))_N))_N)’
    Trans coercion mis-match: Sym co_abMg ; Sym co_abMF
      '["m"] ':/ '[]
      Unpack (Base "m")
      Any
      Unpack Any
*** Offending Program ***
...
```

**Comment by philderbeast** [comment]
With `ghc-8.4.3` and `ghc-8.6.1`, if I exclude the rational examples, the build stops on other problems, such as;

```
/.../uom-plugin-examples/Examples.hs:81:21: error:
    • Couldn't match type ‘fsk4’ with ‘(fsk3 *: (fsk3 *: One)) /: One’
        arising from a use of ‘convert’
      The type variables ‘fsk3’, ‘fsk4’ are ambiguous
    • In the expression:
        convert
          ((Data.UnitsOfMeasure.Internal.MkQuantity ::
              a_a64F -> Quantity a_a64F ((^:) (MkUnit "ft") 2))
             5)
      In an equation for ‘anotherConversion’:
          anotherConversion
            = convert
                ((Data.UnitsOfMeasure.Internal.MkQuantity ::
                    a_a64F -> Quantity a_a64F ((^:) (MkUnit "ft") 2))
                   5)
   |
81 | anotherConversion = convert [u| 5 ft^2 |]
```

**Comment by philderbeast** [comment]
As for the tests, these pass with;

```
> stack test --stack-yaml=stack-8.0.1.yaml
> stack test --stack-yaml=stack-8.0.2.yaml
> stack test --stack-yaml=stack-8.2.2.yaml
```

The failure with `ghc-8.4.3` is;

```
> stack test --stack-yaml=stack-8.4.3.yaml
    /Users/pdejoux/dev/src/haskell/uom-plugin-ghc-api/uom-plugin/tests/Defs.hs:26:8: error:
        • Occurs check: cannot construct the infinite type:
            fsk0 ~ fsk0 /: fsk0
            arising from a use of ‘convert’
          The type variable ‘fsk0’ is ambiguous
        • In the expression: convert
          In an equation for ‘dime’: dime = convert
       |
    26 | dime = convert
       |        ^^^^^^^

    /Users/pdejoux/dev/src/haskell/uom-plugin-ghc-api/uom-plugin/tests/Defs.hs:26:8: error:
        • Couldn't match type ‘(fsk0 *: fsk0) /: fsk0’ with ‘fsk0 /: fsk0’
            arising from a use of ‘convert’
          NB: ‘/:’ is a non-injective type family
          The type variable ‘fsk0’ is ambiguous
        • In the expression: convert
          In an equation for ‘dime’: dime = convert
       |
    26 | dime = convert
       |        ^^^^^^^
```

**Comment by adamgundry** [comment]
Wow, great work! I'm not opposed to dropping 7.x support. Indeed the plugin is rather broken on 8.4 and 8.6 it seems, because of the flatten-skolem issue (#43) and perhaps something else that is leading to core lint errors. Being able to build it across all the versions is a helpful first step though.

For now, perhaps we should set up CI to build the `uom-plugin` library component but not the examples/tests on 8.4 and 8.6? I'll continue trying to pin down the GHC changes.

**Comment by adamgundry** [comment]
> Please assign this issue to me.

I've invited you as a collaborator to this repo, so feel free to accept and claim it. :wink:
