### ISSUE TITLE
Converting between identical units

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#23]
Should this be possible? 

Under similar situations GHC fails with the infinite type `u ~ Pack (Unpack u)`.

This currently fails to compile with ghc-7.10.3 and ghc-8.0.1:

``` haskell
{-# OPTIONS_GHC -fplugin Data.UnitsOfMeasure.Plugin #-}

import           Data.UnitsOfMeasure

convert' :: Quantity a u -> Quantity a u
convert' = convert
```

```
Foo.hs:6:12: error:
    • Couldn't match type ‘u’ with ‘Pack (Unpack u)’
        arising from a use of ‘convert’
      ‘u’ is a rigid type variable bound by
        the type signature for:
          convert' :: forall a (u :: Unit). Quantity a u -> Quantity a u
        at Foo.hs:5:13
    • In the expression: convert
      In an equation for ‘convert'’: convert' = convert
    • Relevant bindings include
        convert' :: Quantity a u -> Quantity a u (bound at Foo.hs:6:1)

```

**Comment by adamgundry** [comment]
At the moment, you can define

```
convert' :: (Fractional a, Good u) => Quantity a u -> Quantity a u
convert' = convert
```

where `Good` captures the additional structure on units required to be able to calculate the conversion ratio. It is defined in `Data.UnitsOfMeasure.Convert`:

```
type Good u = (u ~ Pack (Unpack u), KnownUnit (Unpack u), HasCanonical (Unpack u))
```

I believe the plugin could be modified to automatically solve constraints of the form `u ~ Pack (Unpack u)`, because they should be identified by the equational theory of units. Note that the constraint `u ~ Pack (Unpack u)` doesn't actually lead to an infinite type, because `Pack` and `Unpack` are type families (defined by `uom-plugin`).

In principle, getting rid of the other constraints on `convert` for the case of identical units is possible (at least for "identical up to GHC's built-in equational theory", but perhaps not for "identical up to the equational theory of units"). It's likely to be more difficult and complicate type inference for `convert`, because the type-checker would first need to determine whether the units are identical, then would choose whether to use the existing conversion machinery or simply return the value unchanged. I suspect this is more trouble than it's worth.

**Comment by expipiplus1** [comment]
ok, that's no problem. Thanks for the explanation.
