### PR TITLE
Support GHC 9.0 and 9.2

### LINKED ISSUE #43: Plugin broken on GHC 8.4.2
There are lots of unsolved constraints involving flattening skolems. Perhaps [Trac #15147](https://ghc.haskell.org/trac/ghc/ticket/15147) is related?

```
RationalExamples.hs:53:13: error:
    • Couldn't match type ‘Data.UnitsOfMeasure.Convert.ToCBU
                             (Unpack fsk1)’
                     with ‘(fsk0 *: One) /: One’
        arising from a use of ‘convert’
      The type variables ‘fsk1’, ‘fsk0’ are ambiguous
    • In the expression: convert $ (1 / 60) *: lngMinute
      In an equation for ‘lngSecond’:
          lngSecond = convert $ (1 / 60) *: lngMinute
   |
53 | lngSecond = convert $ (1 / 60) *: lngMinute
```

### LINKED ISSUE #79: Support GHC 9.2
It looks like the removal of type family application flattening in GHC 9.2 means the plugin should start to work again. I have a prototype on the `ghc-9.2` branch that passes the existing testsuite. I'll try to produce a version that is compatible with 9.2.

I'm wondering about dropping support for some or all old GHC versions, because it would be simpler not to bother with so many backwards-compatibility hacks. @philderbeast do you have an opinion on which GHC versions should be supported?

### PR DESCRIPTION
**Pull request by adamgundry**
In the process of making the plugin work on GHC 9.2 I seem to have accidentally made it work on GHC 9.0 as well. I've also added Github Actions support on GHC 9.0. Fixes #43 and fixes #79.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,10 +1,8 @@
...
+The `uom-plugin` library adds support for units of measure to GHC as a type-checker plugin.  See [Data.UnitsOfMeasure.Tutorial](https://github.com/adamgundry/uom-plugin/blob/master/uom-plugin/src/Data/UnitsOfMeasure/Tutorial.hs) for an introduction to the library, and [the accompanying paper](http://adam.gundry.co.uk/pub/typechecker-plugins/) for more background.  An example of a package that uses the library is given in [uom-plugin-examples](uom-plugin-examples).
 
-The library has been tested with GHC `7.10.3`, `8.0.2` & `8.2.2`.
-
-:warning: Please don't use this plugin with later versions of GHC as it will likely fail to solve constraints, [#43][i43].
+The latest version of the library is tested with GHC 9.0.1, and should work with 9.2.1. Older versions of `uom-plugin` (0.3 and earlier) work with the GHC 7.10, 8.0 and 8.2 series. There are no versions supporting GHC 8.4 to 8.10 ([#43][i43]).
```
Comment (philderbeast) [inline README.md:6]: Could we say something in the readme about needing more iterations in GHC `9.0.1` than `9.2.0`?

    {-# OPTIONS_GHC -fconstraint-solver-iterations=6 #-}

**Comment by philderbeast** [comment]
I'm trying to compile flare-timing against this branch of the `uom-plugin` but hit a compile error when using `convert` compiling with stack and `resolver: nightly-2021-06-24 (ghc-9.0.1)`, something I don't see with `resolver: lts-11.22 (ghc-8.2.2):`

https://github.com/BlockScope/flare-timing/blob/64a80131ae4b8bd6541bc663f20bc544fae600de/lang-haskell/latlng/library/Flight/LatLng/Alt.hs#L27-L31

```
stack build --stack-yaml=lang-haskell/stack-9.0.1.yaml
Warning: /.../stack-9.0.1.yaml: Unrecognized field in ProjectAndConfigMonoid: tested-with
flight-latlng> configure (lib)
flight-latlng> Configuring flight-latlng-0.1.0...
flight-latlng> build (lib)
flight-latlng> Preprocessing library for flight-latlng-0.1.0..
flight-latlng> Building library for flight-latlng-0.1.0..
flight-latlng> [ 3 of 13] Compiling Flight.LatLng.Alt
flight-latlng>
flight-latlng> /.../latlng/library/Flight/LatLng/Alt.hs:31:17: error:
flight-latlng>     • Couldn't match type: Data.UnitsOfMeasure.Internal.Pack
flight-latlng>                              (Data.UnitsOfMeasure.Internal.Unpack (Base "m"))
flight-latlng>                      with: Base "m"
flight-latlng>         arising from a use of ‘convert’
flight-latlng>     • In the expression: convert x
flight-latlng>       In an equation for ‘y’: y = convert x
flight-latlng>       In an equation for ‘toJSON’:
flight-latlng>           toJSON (Alt x)
flight-latlng>             = toJSON $ ViaQ (Alt y)
flight-latlng>             where
flight-latlng>                 y :: Quantity Double (Data.UnitsOfMeasure.Internal.MkUnit "m")
flight-latlng>                 y = convert x
flight-latlng>    |
flight-latlng> 31 |             y = convert x
flight-latlng>    |                 ^^^^^^^^^
flight-latlng>
flight-latlng> /.../latlng/library/Flight/LatLng/Alt.hs:36:23: error:
flight-latlng>     • Couldn't match type: Data.UnitsOfMeasure.Internal.Pack
flight-latlng>                              (Data.UnitsOfMeasure.Internal.Unpack (Base "m"))
flight-latlng>                      with: Base "m"
flight-latlng>         arising from a use of ‘convert’
flight-latlng>     • In the second argument of ‘($)’, namely ‘convert x’
flight-latlng>       In the first argument of ‘return’, namely ‘(Alt $ convert x)’
flight-latlng>       In a stmt of a 'do' block: return (Alt $ convert x)
flight-latlng>    |
flight-latlng> 36 |         return (Alt $ convert x)
flight-latlng>    |                       ^^^^^^^^^
```

I've made a reproduction of this failure in the `Z` module. I'll follow up with pull requests, one each for `ghc-8.2.2` and `ghc-9.0.1`

**Comment by adamgundry** [comment]
Closing in favour of #93.
